steps:
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "${_ENV}", ".env"]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/book-backend: --port 5000', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/book-backend']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'book-backend',
        '--image',
        'gcr.io/$PROJECT_ID/book-backend',
        '--region',
        'asia-southeast2',
        '--port',
        '5000',
        '--platform',
        'managed',
        '--allow-unauthenticated',
      ]
 